networks:
  tri-seed-net:
    driver: bridge
services:
  tri-seed-1:
    container_name: tri-seed-1
    environment:
      TOR_SOCKS_PORT: '9050'
      TRI_ALLOW_BACKUP_EXPORT: '0'
      TRI_ALLOW_RESEED: '0'
      TRI_ALLOW_SEND_BROADCAST: '0'
      TRI_ALLOW_WALLET_UNLOCK: '0'
      TRI_BIN: /tri/bin/trianglesd
      TRI_BIN_DIR: /tri/bin
      TRI_BIN_SHA256: sKIP
      TRI_CACHE_DIR: /tri/data/cache
      TRI_CANONICAL_RPC_PASSWORD: xK7mNp4QvR8sWjY2bTdL9eAf
      TRI_CANONICAL_RPC_URL: http://jbpfhe7zw3qm67wy3j2ayysp3mnrjobopthnko3b3sgahqtecblwqmid.onion:19112
      TRI_CANONICAL_RPC_USER: trianglesrpc
      TRI_ENABLE_WRITE_OPS: '0'
      TRI_INSTANCE_ID: tri-seed-1
      TRI_LIB_DIR: /tri/data/lib
      TRI_MODE: seed
      TRI_NODE_NAME: tri-seed-1
      TRI_ROLE: seed
      TRI_RPCPASSWORD: triSEED2026
      TRI_RPCUSER: triseed
      TRI_SEED_ISOLATION: '1'
      TRI_SEED_MODE: '1'
      TRI_SEED_TRUSTED_PEERS: 6ygpphp2qsucwvhwefv6h6ehvk6zjf7b7zdp4ggkzjjwe76cg6jwm7id.onion:24112,jbpfhe7zw3qm67wy3j2ayysp3mnrjobopthnko3b3sgahqtecblwqmid.onion:24112
      TRI_STAKE_ENABLED: '0'
      TRI_VERSION: 5.8.5
    image: samiahmed7777/tridock:walletfix2
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 10m
    networks:
    - tri-seed-net
    ports:
    - 24112:24112
    restart: unless-stopped
    volumes:
    - /root/tri-seed-nodes/data/seed-1:/tri/data
    - /root/tri-seed-nodes/bin/seed-1:/tri/bin
    - tri-seed-1-state:/tri/state
    - tri-seed-1-logs:/tri/logs
    command: []
  tri-seed-2:
    container_name: tri-seed-2
    environment:
      TOR_SOCKS_PORT: '9050'
      TRI_ALLOW_BACKUP_EXPORT: '0'
      TRI_ALLOW_RESEED: '0'
      TRI_ALLOW_SEND_BROADCAST: '0'
      TRI_ALLOW_WALLET_UNLOCK: '0'
      TRI_BIN: /tri/bin/trianglesd
      TRI_BIN_DIR: /tri/bin
      TRI_BIN_SHA256: sKIP
      TRI_CACHE_DIR: /tri/data/cache
      TRI_CANONICAL_RPC_PASSWORD: xK7mNp4QvR8sWjY2bTdL9eAf
      TRI_CANONICAL_RPC_URL: http://jbpfhe7zw3qm67wy3j2ayysp3mnrjobopthnko3b3sgahqtecblwqmid.onion:19112
      TRI_CANONICAL_RPC_USER: trianglesrpc
      TRI_ENABLE_WRITE_OPS: '0'
      TRI_INSTANCE_ID: tri-seed-2
      TRI_LIB_DIR: /tri/data/lib
      TRI_MODE: seed
      TRI_NODE_NAME: tri-seed-2
      TRI_ROLE: seed
      TRI_RPCPASSWORD: triSEED2026
      TRI_RPCUSER: triseed
      TRI_SEED_ISOLATION: '1'
      TRI_SEED_MODE: '1'
      TRI_SEED_TRUSTED_PEERS: 6ygpphp2qsucwvhwefv6h6ehvk6zjf7b7zdp4ggkzjjwe76cg6jwm7id.onion:24112,jbpfhe7zw3qm67wy3j2ayysp3mnrjobopthnko3b3sgahqtecblwqmid.onion:24112
      TRI_STAKE_ENABLED: '0'
      TRI_VERSION: 5.8.5
    image: samiahmed7777/tridock:walletfix2
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 10m
    networks:
    - tri-seed-net
    ports:
    - 24113:24112
    restart: unless-stopped
    volumes:
    - /root/tri-seed-nodes/data/seed-2:/tri/data
    - /root/tri-seed-nodes/bin/seed-2:/tri/bin
    - tri-seed-2-state:/tri/state
    - tri-seed-2-logs:/tri/logs
    command: []
  tri-seed-3:
    container_name: tri-seed-3
    environment:
      TOR_SOCKS_PORT: '9050'
      TRI_ALLOW_BACKUP_EXPORT: '0'
      TRI_ALLOW_RESEED: '0'
      TRI_ALLOW_SEND_BROADCAST: '0'
      TRI_ALLOW_WALLET_UNLOCK: '0'
      TRI_BIN: /tri/bin/trianglesd
      TRI_BIN_DIR: /tri/bin
      TRI_BIN_SHA256: sKIP
      TRI_CACHE_DIR: /tri/data/cache
      TRI_CANONICAL_RPC_PASSWORD: xK7mNp4QvR8sWjY2bTdL9eAf
      TRI_CANONICAL_RPC_URL: http://jbpfhe7zw3qm67wy3j2ayysp3mnrjobopthnko3b3sgahqtecblwqmid.onion:19112
      TRI_CANONICAL_RPC_USER: trianglesrpc
      TRI_ENABLE_WRITE_OPS: '0'
      TRI_INSTANCE_ID: tri-seed-3
      TRI_LIB_DIR: /tri/data/lib
      TRI_MODE: seed
      TRI_NODE_NAME: tri-seed-3
      TRI_ROLE: seed
      TRI_RPCPASSWORD: triSEED2026
      TRI_RPCUSER: triseed
      TRI_SEED_ISOLATION: '1'
      TRI_SEED_MODE: '1'
      TRI_SEED_TRUSTED_PEERS: 6ygpphp2qsucwvhwefv6h6ehvk6zjf7b7zdp4ggkzjjwe76cg6jwm7id.onion:24112,jbpfhe7zw3qm67wy3j2ayysp3mnrjobopthnko3b3sgahqtecblwqmid.onion:24112
      TRI_STAKE_ENABLED: '0'
      TRI_VERSION: 5.8.5
    image: samiahmed7777/tridock:walletfix2
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 10m
    networks:
    - tri-seed-net
    ports:
    - 24114:24112
    restart: unless-stopped
    volumes:
    - /root/tri-seed-nodes/data/seed-3:/tri/data
    - /root/tri-seed-nodes/bin/seed-3:/tri/bin
    - tri-seed-3-state:/tri/state
    - tri-seed-3-logs:/tri/logs
    command: []
  tri-seed-4:
    container_name: tri-seed-4
    environment:
      TOR_SOCKS_PORT: '9050'
      TRI_ALLOW_BACKUP_EXPORT: '0'
      TRI_ALLOW_RESEED: '0'
      TRI_ALLOW_SEND_BROADCAST: '0'
      TRI_ALLOW_WALLET_UNLOCK: '0'
      TRI_BIN: /tri/bin/trianglesd
      TRI_BIN_DIR: /tri/bin
      TRI_BIN_SHA256: sKIP
      TRI_CACHE_DIR: /tri/data/cache
      TRI_CANONICAL_RPC_PASSWORD: xK7mNp4QvR8sWjY2bTdL9eAf
      TRI_CANONICAL_RPC_URL: http://jbpfhe7zw3qm67wy3j2ayysp3mnrjobopthnko3b3sgahqtecblwqmid.onion:19112
      TRI_CANONICAL_RPC_USER: trianglesrpc
      TRI_ENABLE_WRITE_OPS: '0'
      TRI_INSTANCE_ID: tri-seed-4
      TRI_LIB_DIR: /tri/data/lib
      TRI_MODE: seed
      TRI_NODE_NAME: tri-seed-4
      TRI_ROLE: seed
      TRI_RPCPASSWORD: triSEED2026
      TRI_RPCUSER: triseed
      TRI_SEED_ISOLATION: '1'
      TRI_SEED_MODE: '1'
      TRI_SEED_TRUSTED_PEERS: 6ygpphp2qsucwvhwefv6h6ehvk6zjf7b7zdp4ggkzjjwe76cg6jwm7id.onion:24112,jbpfhe7zw3qm67wy3j2ayysp3mnrjobopthnko3b3sgahqtecblwqmid.onion:24112
      TRI_STAKE_ENABLED: '0'
      TRI_VERSION: 5.8.5
    image: samiahmed7777/tridock:walletfix2
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 10m
    networks:
    - tri-seed-net
    ports:
    - 24115:24112
    restart: unless-stopped
    volumes:
    - /root/tri-seed-nodes/data/seed-4:/tri/data
    - /root/tri-seed-nodes/bin/seed-4:/tri/bin
    - tri-seed-4-state:/tri/state
    - tri-seed-4-logs:/tri/logs
    command: []
volumes:
  tri-seed-1-logs: null
  tri-seed-1-state: null
  tri-seed-2-logs: null
  tri-seed-2-state: null
  tri-seed-3-logs: null
  tri-seed-3-state: null
  tri-seed-4-logs: null
  tri-seed-4-state: null
