services:
  tridock:
    build: .
    image: samiahmed7777/tridock:latest
    container_name: tridock
    restart: unless-stopped
    ports:
      - "24112:24112/tcp"
      - "24112:24112/udp"
    environment:
      TRI_MODE: full
      TRI_NODE_NAME: tridock
      TRI_VERSION: "5.7.5"
      TRI_TOR_ENABLED: "1"
      TRI_BOOTSTRAP_ENABLED: "1"
      TRI_PREFER_BOOTSTRAP: "1"
      TRI_BOOTSTRAP_TIMEOUT: "30"
      TRI_BOOTSTRAP_MIN_BLOCK_BYTES: "100000000"
      TRI_BOOTSTRAP_MIN_LDB_COUNT: "300"
      TRI_BOOTSTRAP_URLS: "http://100.104.4.5:8081/bootstrap-new.tar.gz,http://bootstrap.cryptographic-triangles.org:8080/triangles-bootstrap.tar.gz"
      TRI_RELEASE_BASE_URL: "https://github.com/TrianglesProject/triangles/releases/download"
      TRI_RELEASE_FILENAME: "triangles-5.7.5-linux64.tar.gz"
      TRI_BIN_DOWNLOAD_URL: ""
      TRI_BIN_FALLBACK_URLS: ""
      TRI_BIN_SHA256: ""
      TRI_RPCUSER: tri
      TRI_RPCPASSWORD: change-me
      TRI_RPCPORT: "19112"
      TRI_MAX_CONNECTIONS: "64"
      TRI_DBCACHE: "512"
    volumes:
      - tri_data:/tri/data
      - tri_bootstrap:/tri/bootstrap
      - tri_cache:/tri/cache
      - ./tri-bin:/tri/bin
      - ./tri-lib:/tri/lib

volumes:
  tri_data:
  tri_bootstrap:
  tri_cache:
