services:
  tridock-staking:
    image: samiahmed7777/tridock:latest
    container_name: tridock-staking
    restart: unless-stopped
    ports:
      - "24112:24112/tcp"
      - "24112:24112/udp"
    environment:
      TRI_MODE: staking
      TRI_NODE_NAME: tridock-staking
      TRI_STAKE_ENABLED: "1"
      TRI_TOR_ENABLED: "1"
      TRI_BOOTSTRAP_ENABLED: "1"
      TRI_BOOTSTRAP_URLS: "https://bootstrap.cryptographic-triangles.org/tri-bootstrap.tar.gz"
      TRI_RPCUSER: tri
      TRI_RPCPASSWORD: change-me
    volumes:
      - tri_staking_data:/tri/data
      - tri_staking_bootstrap:/tri/bootstrap

volumes:
  tri_staking_data:
  tri_staking_bootstrap:
